// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: greeting.proto

package greet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetMeClient is the client API for GreetMe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetMeClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Namaste(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type greetMeClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetMeClient(cc grpc.ClientConnInterface) GreetMeClient {
	return &greetMeClient{cc}
}

func (c *greetMeClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/GreetMe/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetMeClient) Namaste(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/GreetMe/Namaste", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetMeServer is the server API for GreetMe service.
// All implementations must embed UnimplementedGreetMeServer
// for forward compatibility
type GreetMeServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	Namaste(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedGreetMeServer()
}

// UnimplementedGreetMeServer must be embedded to have forward compatible implementations.
type UnimplementedGreetMeServer struct {
}

func (UnimplementedGreetMeServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedGreetMeServer) Namaste(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Namaste not implemented")
}
func (UnimplementedGreetMeServer) mustEmbedUnimplementedGreetMeServer() {}

// UnsafeGreetMeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetMeServer will
// result in compilation errors.
type UnsafeGreetMeServer interface {
	mustEmbedUnimplementedGreetMeServer()
}

func RegisterGreetMeServer(s grpc.ServiceRegistrar, srv GreetMeServer) {
	s.RegisterService(&GreetMe_ServiceDesc, srv)
}

func _GreetMe_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetMeServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreetMe/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetMeServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetMe_Namaste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetMeServer).Namaste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreetMe/Namaste",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetMeServer).Namaste(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetMe_ServiceDesc is the grpc.ServiceDesc for GreetMe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetMe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GreetMe",
	HandlerType: (*GreetMeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GreetMe_Hello_Handler,
		},
		{
			MethodName: "Namaste",
			Handler:    _GreetMe_Namaste_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeting.proto",
}
